### PR TITLE
Add CodeFactor badge and .NET core prerequisites

### PR DESCRIPTION
**Pull request by jannesrsa**
I've added one more badge, the CodeFactor badge pointing to https://www.codefactor.io.
I found it useful for spotting duplicate code. You would have to change the URL, but you can have a look at my branch's for an idea of what it does.

https://www.codefactor.io/repository/github/jannesrsa/chasm

Also added a Prerequisites section to the README.

### CODE REVIEW

**Comment by jcdickinson** [comment]
Awesome stuff! I'm just waiting on an OSS address from IT so that I can sign up to codecov, codefactor, etc. under an umbrella K2 account. I'll merge this once that's done.

**Comment by grant-d** [comment]
I agree. This is very cool, I already used the report to fix some duplicate-code issues in source

**Comment by jannesrsa** [comment]
I removed some unit tests from this branch to separate it from the CodeFactor change.
The unit tests will be moved to another branch.

**Comment by grant-d** [comment]
I am merging this in using @jannesrsa's account. We will flip to our own account once we have the email address

**Pull request merged**
